package com.plantdesk.workorder;

import com.plantdesk.asset.Asset;
import com.plantdesk.tenancy.TenantFilters;
import com.plantdesk.tenancy.TenantScopedEntity;
import com.plantdesk.user.User;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import org.hibernate.annotations.Filter;

import java.time.Instant;
import java.util.EnumSet;
import java.util.Set;
import java.util.UUID;

/**
 * A job card. Status has no setter: it changes only through {@link #apply}, which checks
 * the transition table in {@link WorkOrderAction} and the guards (assignee, labour,
 * failure code) that make a plant job card complete.
 */
@Entity
@Table(name = "work_orders")
@Filter(name = TenantFilters.ASSIGNEE, condition = "assignee_id = :" + TenantFilters.ASSIGNEE_PARAM)
public class WorkOrder extends TenantScopedEntity {

    @Column(nullable = false, updatable = false)
    private String number;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "asset_id", nullable = false, updatable = false)
    private Asset asset;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, updatable = false)
    private WorkOrderType type;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Priority priority;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private WorkOrderStatus status = WorkOrderStatus.OPEN;

    @Column(nullable = false)
    private String title;

    private String description;

    @Enumerated(EnumType.STRING)
    @Column(name = "failure_code")
    private FailureCode failureCode;

    // Null when generated by the PM scheduler.
    @Column(name = "raised_by", updatable = false)
    private UUID raisedBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assignee_id")
    private User assignee;

    @Column(name = "raised_at", nullable = false, updatable = false)
    private Instant raisedAt;

    @Column(name = "started_at")
    private Instant startedAt;

    @Column(name = "completed_at")
    private Instant completedAt;

    @Column(name = "closed_at")
    private Instant closedAt;

    // The window the asset was unavailable. For a breakdown it opens when the failure
    // happened (which may be before anyone raised the order) and closes at return to service.
    @Column(name = "downtime_start")
    private Instant downtimeStart;

    @Column(name = "downtime_end")
    private Instant downtimeEnd;

    @Column(name = "hold_reason")
    private String holdReason;

    @Column(name = "closure_note")
    private String closureNote;

    @Column(name = "pm_schedule_id", updatable = false)
    private UUID pmScheduleId;

    @Column(name = "pm_sequence", updatable = false)
    private Integer pmSequence;

    @Column(name = "due_at", updatable = false)
    private Instant dueAt;

    @Column(name = "due_running_minutes", updatable = false)
    private Long dueRunningMinutes;

    @Column(name = "running_minutes_at_completion")
    private Long runningMinutesAtCompletion;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    protected WorkOrder() {}

    private WorkOrder(String number, Asset asset, WorkOrderType type, Priority priority, String title,
                      String description, UUID raisedBy, Instant raisedAt) {
        this.number = number;
        this.asset = asset;
        this.type = type;
        this.priority = priority;
        this.title = title;
        this.description = description;
        this.raisedBy = raisedBy;
        this.raisedAt = raisedAt;
        this.createdAt = raisedAt;
    }

    public static WorkOrder breakdown(String number, Asset asset, Priority priority, String title, String description,
                                      FailureCode failureCode, Instant failedAt, UUID raisedBy, Instant now) {
        WorkOrder wo = new WorkOrder(number, asset, WorkOrderType.BREAKDOWN, priority, title, description, raisedBy, now);
        wo.failureCode = failureCode;
        Instant start = failedAt == null ? now : failedAt;
        if (start.isAfter(now)) {
            throw new IllegalArgumentException("Failure time cannot be in the future");
        }
        wo.downtimeStart = start;
        return wo;
    }

    public static WorkOrder preventive(String number, Asset asset, Priority priority, String title, String description,
                                       UUID raisedBy, Instant now) {
        return new WorkOrder(number, asset, WorkOrderType.PREVENTIVE, priority, title, description, raisedBy, now);
    }

    public static WorkOrder fromPmSchedule(String number, Asset asset, Priority priority, String title, String description,
                                           UUID pmScheduleId, int pmSequence, Instant dueAt, Long dueRunningMinutes,
                                           UUID raisedBy, Instant now) {
        WorkOrder wo = preventive(number, asset, priority, title, description, raisedBy, now);
        wo.pmScheduleId = pmScheduleId;
        wo.pmSequence = pmSequence;
        wo.dueAt = dueAt;
        wo.dueRunningMinutes = dueRunningMinutes;
        return wo;
    }

    /** Facts the state machine needs that live outside this row. */
    public record TransitionInput(Instant now, long labourMinutes, String note, FailureCode failureCode) {}

    public void apply(WorkOrderAction action, TransitionInput in) {
        if (!action.allowedFrom().contains(status)) {
            throw new InvalidTransitionException(String.format(
                    "Cannot %s work order %s: it is %s. %s is only allowed from %s.",
                    action, number, status, action, action.allowedFrom()));
        }
        switch (action) {
            case START -> {
                if (assignee == null) {
                    throw new InvalidTransitionException("Assign a technician to " + number + " before starting work.");
                }
                if (startedAt == null) {
                    startedAt = in.now();
                }
                holdReason = null;
            }
            case HOLD -> holdReason = requireNote(in, "Give a hold reason, e.g. awaiting spares or shutdown permit.");
            case RETURN_TO_SERVICE -> {
                if (in.labourMinutes() <= 0) {
                    throw new InvalidTransitionException(
                            "Record labour hours on " + number + " before returning the equipment to service.");
                }
                if (in.failureCode() != null) {
                    failureCode = in.failureCode();
                }
                if (type == WorkOrderType.BREAKDOWN && failureCode == null) {
                    throw new InvalidTransitionException(
                            "Record a failure code on breakdown " + number + " before returning to service.");
                }
                completedAt = in.now();
                if (downtimeStart != null && downtimeEnd == null) {
                    downtimeEnd = in.now();
                }
                runningMinutesAtCompletion = asset.getRunningMinutes();
            }
            case CLOSE -> {
                closedAt = in.now();
                closureNote = in.note();
            }
            case REWORK -> {
                completedAt = null;
                closureNote = requireNote(in, "Say what needs reworking before sending the job back.");
            }
            case CANCEL -> closureNote = requireNote(in, "Give a reason for cancelling " + number + ".");
        }
        status = action.target();
    }

    /** Actions that are valid from the current state, before role checks. */
    public Set<WorkOrderAction> availableActions() {
        Set<WorkOrderAction> result = EnumSet.noneOf(WorkOrderAction.class);
        for (WorkOrderAction a : WorkOrderAction.values()) {
            if (a.allowedFrom().contains(status)) {
                result.add(a);
            }
        }
        return result;
    }

    public void assign(User technician) {
        if (!status.isOutstanding()) {
            throw new InvalidTransitionException("Cannot reassign " + number + ": it is " + status + ".");
        }
        this.assignee = technician;
    }

    public void correctDowntime(Instant start, Instant end) {
        if (start == null || (end != null && end.isBefore(start))) {
            throw new IllegalArgumentException("Downtime must have a start, and end cannot be before start");
        }
        this.downtimeStart = start;
        this.downtimeEnd = end;
    }

    public boolean isOverdue(Instant now) {
        if (!status.isOutstanding()) {
            return false;
        }
        boolean pastDate = dueAt != null && now.isAfter(dueAt);
        boolean pastHours = dueRunningMinutes != null && asset.getRunningMinutes() > dueRunningMinutes;
        return pastDate || pastHours;
    }

    private static String requireNote(TransitionInput in, String message) {
        if (in.note() == null || in.note().isBlank()) {
            throw new InvalidTransitionException(message);
        }
        return in.note().trim();
    }

    public String getNumber() { return number; }
    public Asset getAsset() { return asset; }
    public WorkOrderType getType() { return type; }
    public Priority getPriority() { return priority; }
    public WorkOrderStatus getStatus() { return status; }
    public String getTitle() { return title; }
    public String getDescription() { return description; }
    public FailureCode getFailureCode() { return failureCode; }
    public UUID getRaisedBy() { return raisedBy; }
    public User getAssignee() { return assignee; }
    public Instant getRaisedAt() { return raisedAt; }
    public Instant getStartedAt() { return startedAt; }
    public Instant getCompletedAt() { return completedAt; }
    public Instant getClosedAt() { return closedAt; }
    public Instant getDowntimeStart() { return downtimeStart; }
    public Instant getDowntimeEnd() { return downtimeEnd; }
    public String getHoldReason() { return holdReason; }
    public String getClosureNote() { return closureNote; }
    public UUID getPmScheduleId() { return pmScheduleId; }
    public Integer getPmSequence() { return pmSequence; }
    public Instant getDueAt() { return dueAt; }
    public Long getDueRunningMinutes() { return dueRunningMinutes; }
}
