-- =============================================================================
-- V3: spare parts, work orders, labour, parts consumption.
-- =============================================================================

CREATE TABLE spare_parts (
    id            uuid PRIMARY KEY,
    tenant_id     uuid          NOT NULL REFERENCES tenants (id),
    part_number   varchar(64)   NOT NULL,
    description   varchar(300)  NOT NULL,
    -- Fractional quantities are real: litres of turbine oil, metres of cable.
    unit          varchar(8)    NOT NULL CHECK (unit IN ('EA', 'SET', 'L', 'KG', 'M')),
    stock_qty     numeric(12, 3) NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
    reorder_point numeric(12, 3) NOT NULL DEFAULT 0 CHECK (reorder_point >= 0),
    unit_cost     numeric(12, 2) NOT NULL CHECK (unit_cost >= 0),
    bin_location  varchar(32),
    created_at    timestamptz   NOT NULL DEFAULT now(),
    version       bigint        NOT NULL DEFAULT 0,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, part_number)
);

CREATE TABLE work_order_counters (
    tenant_id  uuid    NOT NULL REFERENCES tenants (id),
    year       integer NOT NULL,
    last_value integer NOT NULL,
    PRIMARY KEY (tenant_id, year)
);

CREATE TABLE work_orders (
    id                            uuid PRIMARY KEY,
    tenant_id                     uuid         NOT NULL REFERENCES tenants (id),
    number                        varchar(20)  NOT NULL,
    asset_id                      uuid         NOT NULL,
    type                          varchar(16)  NOT NULL CHECK (type IN ('BREAKDOWN', 'PREVENTIVE')),
    priority                      varchar(16)  NOT NULL CHECK (priority IN ('EMERGENCY', 'HIGH', 'MEDIUM', 'LOW')),
    status                        varchar(16)  NOT NULL
        CHECK (status IN ('OPEN', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CLOSED', 'CANCELLED')),
    title                         varchar(200) NOT NULL,
    description                   text,
    failure_code                  varchar(8)
        CHECK (failure_code IN ('E01', 'E02', 'E03', 'E04', 'M01', 'M02', 'M03', 'M04', 'M05',
                                'I01', 'I02', 'O01', 'X01')),
    -- NULL = generated by the PM scheduler. Better an honest NULL than a fake "system" user
    -- that would show up in technician lists and labour reports.
    raised_by                     uuid,
    assignee_id                   uuid,
    raised_at                     timestamptz  NOT NULL,
    started_at                    timestamptz,
    completed_at                  timestamptz,
    closed_at                     timestamptz,
    downtime_start                timestamptz,
    downtime_end                  timestamptz,
    hold_reason                   varchar(300),
    closure_note                  text,
    pm_schedule_id                uuid,
    pm_sequence                   integer,
    due_at                        timestamptz,
    due_running_minutes           bigint,
    running_minutes_at_completion bigint,
    created_at                    timestamptz  NOT NULL DEFAULT now(),
    version                       bigint       NOT NULL DEFAULT 0,
    UNIQUE (tenant_id, id),
    UNIQUE (tenant_id, number),
    FOREIGN KEY (tenant_id, asset_id) REFERENCES assets (tenant_id, id),
    FOREIGN KEY (tenant_id, raised_by) REFERENCES users (tenant_id, id),
    FOREIGN KEY (tenant_id, assignee_id) REFERENCES users (tenant_id, id),
    CONSTRAINT downtime_window_valid
        CHECK (downtime_end IS NULL OR (downtime_start IS NOT NULL AND downtime_end >= downtime_start)),
    -- Belt and braces under the Java state machine: these states need someone on the job.
    CONSTRAINT worked_orders_have_assignee
        CHECK (status IN ('OPEN', 'CANCELLED') OR assignee_id IS NOT NULL),
    -- A breakdown cannot be returned to service without saying what failed.
    CONSTRAINT completed_breakdowns_have_failure_code
        CHECK (type <> 'BREAKDOWN' OR status NOT IN ('COMPLETED', 'CLOSED') OR failure_code IS NOT NULL),
    CONSTRAINT pm_link_complete CHECK ((pm_schedule_id IS NULL) = (pm_sequence IS NULL))
);
CREATE INDEX work_orders_status_idx ON work_orders (tenant_id, status);
CREATE INDEX work_orders_asset_idx ON work_orders (tenant_id, asset_id, raised_at);
CREATE INDEX work_orders_assignee_idx ON work_orders (tenant_id, assignee_id);

CREATE TABLE labour_entries (
    id            uuid PRIMARY KEY,
    tenant_id     uuid        NOT NULL REFERENCES tenants (id),
    work_order_id uuid        NOT NULL,
    technician_id uuid        NOT NULL,
    -- Integer minutes, never floating-point hours. 1440 cap = one person cannot book
    -- more than a day against one job in one entry.
    minutes       integer     NOT NULL CHECK (minutes > 0 AND minutes <= 1440),
    work_date     date        NOT NULL,
    note          varchar(300),
    created_at    timestamptz NOT NULL DEFAULT now(),
    version       bigint      NOT NULL DEFAULT 0,
    FOREIGN KEY (tenant_id, work_order_id) REFERENCES work_orders (tenant_id, id),
    FOREIGN KEY (tenant_id, technician_id) REFERENCES users (tenant_id, id)
);
CREATE INDEX labour_entries_wo_idx ON labour_entries (tenant_id, work_order_id);

CREATE TABLE part_consumptions (
    id            uuid PRIMARY KEY,
    tenant_id     uuid           NOT NULL REFERENCES tenants (id),
    work_order_id uuid           NOT NULL,
    spare_part_id uuid           NOT NULL,
    quantity      numeric(12, 3) NOT NULL CHECK (quantity > 0),
    -- Cost captured at the moment of issue. If the part price changes next month,
    -- last month's breakdown must still cost what it cost.
    unit_cost     numeric(12, 2) NOT NULL CHECK (unit_cost >= 0),
    consumed_at   timestamptz    NOT NULL,
    consumed_by   uuid           NOT NULL,
    version       bigint         NOT NULL DEFAULT 0,
    FOREIGN KEY (tenant_id, work_order_id) REFERENCES work_orders (tenant_id, id),
    FOREIGN KEY (tenant_id, spare_part_id) REFERENCES spare_parts (tenant_id, id),
    FOREIGN KEY (tenant_id, consumed_by) REFERENCES users (tenant_id, id)
);
CREATE INDEX part_consumptions_wo_idx ON part_consumptions (tenant_id, work_order_id);

ALTER TABLE spare_parts ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON spare_parts
    USING (tenant_id = app_current_tenant())
    WITH CHECK (tenant_id = app_current_tenant());

ALTER TABLE work_order_counters ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON work_order_counters
    USING (tenant_id = app_current_tenant())
    WITH CHECK (tenant_id = app_current_tenant());

-- Work orders carry the second row rule: a technician sees only what is assigned to them.
-- Enforced here as well as by the Hibernate assignee filter, so even a hand-written
-- native query cannot hand a technician someone else's job card.
ALTER TABLE work_orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON work_orders
    USING (tenant_id = app_current_tenant()
        AND (app_current_role() IS DISTINCT FROM 'TECHNICIAN' OR assignee_id = app_current_user()))
    WITH CHECK (tenant_id = app_current_tenant());

ALTER TABLE labour_entries ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON labour_entries
    USING (tenant_id = app_current_tenant())
    WITH CHECK (tenant_id = app_current_tenant());

ALTER TABLE part_consumptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON part_consumptions
    USING (tenant_id = app_current_tenant())
    WITH CHECK (tenant_id = app_current_tenant());
